apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-monitor
  template:
    metadata:
      labels:
        app: flask-monitor
    spec:
      containers:
      - name: flask-app
        image: flask-monitor:latest
        ports:
        - containerPort: 5000
