name: Testing K3s-monitoring

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Execute run.sh script
      run: |
        sudo ./run.sh

    - name: Verify Kubernetes API
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Wait for pods to be ready
      run: |
        kubectl wait --for=condition=ready pod --all --timeout=120s -n default

    - name: Test application in Kubernetes
      run: |
        kubectl get pods
        kubectl port-forward svc/flask-monitor-service 5000:5000 &
        curl -s http://localhost:5000 | grep "Kubernetes Monitor Running!"
